services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/covid_data_tracker
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379
  redis:
    image: redis:6.2-alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    volumes:
      - '.:/covid_data_tracker'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379
volumes:
  db:
  redis: